#!/bin/sh
#
# iftd.init      Starts iftd
#
# description: Starts and stops iftd
#
### BEGIN INIT INFO

# Source function library.
. /etc/init.d/functions


CONFIGFILE="/etc/iftd/iftd.xml"
LOGFILE="/tmp/iftd.log"
LOCKFILE="/tmp/iftd.pid"

start() {
	echo -n $"Starting iftd: "
   /usr/sbin/iftd -C $CONFIGFILE -L $LOGFILE

   RETVAL=""

   PROCS=$(ps aux | grep "/usr/sbin/iftd" | wc -l)
	if [[ $PROCS == 1 ]]; then
      echo "FAIL"
      RETVAL=255
   else
      echo "success"
      RETVAL=0
   fi
   
	return $RETVAL
}	

stop() {
	echo -n $"Shutting down iftd (fail ok): "
   RETVAL=0
   IFTD_PROCS=$(ps aux | grep "/usr/sbin/iftd" | wc -l)
   if [[ -f $LOCKFILE || $IFTD_PROCS != 1 ]]; then
      PID=$(cat $LOCKFILE 2>/dev/null)

      if [[ $PID != "" ]]; then
         kill $PID 2>/dev/null
         sleep 1
      fi 

      # make absolutely certain that it is dead
      PROCS=$(ps aux | grep "/usr/sbin/iftd" | awk '{print $2}')
      for p in $PROCS; do
         kill -9 $p > /dev/null 2> /dev/null
      done


      rm -f $LOCKFILE
      RETVAL=0
   fi
	echo "success"
	return 0
}	

restart() {
	stop
	start
}	

hup() {
        echo "Sorry, not implemented..."
}

rhstatus() {
        echo "Sorry, not implemented..."
}	


case "$1" in
  start)
  	start
	;;
  stop)
  	stop
	;;
  restart|reload|condrestart)
  	restart
	;;
  status)
  	rhstatus
	;;
  *)
	echo "Usage: $0 {start|stop|restart|reload|condrestart|hup|status}"
	exit 1
esac

exit $?
